name = "ai-capture-analyser"
main = "src/index.ts"
compatibility_date = "2025-08-26"

routes = [
  { pattern = "ai-capture.pierrefouquet.co.uk", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"

[ai]
binding = "AI"

[durable_objects]
bindings = [{ name = "ANALYSIS_OBJECT", class_name = "AnalysisObject" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "AnalysisObject" ]

[observability]
enabled = true

[build]
command = "npm install && npm run build"
watch_dir = "./src"