name = "ai-capture-analyser"
main = "src/index.py"
compatibility_date = "2025-08-26"
compatibility_flags = ["python_workers"]

routes = [
  { pattern = "ai-capture.pierrefouquet.co.uk", custom_domain = true }
]

[site]
bucket = "./public" # Specifies the directory for static assets

[ai]
binding = "AI"

[durable_objects]
bindings = [{ name = "ANALYSIS_OBJECT", class_name = "AnalysisObject" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "AnalysisObject" ]