name = "packet-analyzer"
main = "src/index.py"
compatibility_date = "2025-08-26"

routes = [
  { pattern = "ai-capture.pierrefouquet.co.uk", custom_domain = true }
]

[site]
bucket = "./public" # Specifies the directory for static assets

[ai]
binding = "AI"

[[durable_objects]]
binding = "ANALYSIS_OBJECT"
class_name = "AnalysisObject"

[[durable_objects.migrations]]
tag = "v1"
new_classes = ["AnalysisObject"]
